[tool.poetry]
name = "django-fastapi-app"
version = "0.1.0"
description = ""
authors = ["sergiy <kukaletssergiy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
celery = "^5.6.2"
Django = "^4.1.0"
djangorestframework = "^3.16.1"
django-celery-beat = "^2.8.1"
fastapi = "^0.128.8"
pydantic = "^2.12.5"
email-validator = "^2.3.0"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
whitenoise = "^6.2.0"
psycopg2 = "^2.9.3"
psycopg2-binary = "^2.9.11"
gunicorn = "^21.2.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.5"
Pillow = "^9.1.1"
pytz = "^2022.1"
redis = "^7.1.1"
requests = "^2.32.5"

[tool.poetry.group.dev.dependencies]
black = {version = "^22.10.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"