# Generated by Django 4.2.28 on 2026-02-12 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="updated_at"),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FetchState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_currency", models.CharField(default="ETH", max_length=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="updated_at"),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurrencyStats",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="updated_at"),
                ),
                (
                    "price_usd",
                    models.DecimalField(decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "market_cap_usd",
                    models.DecimalField(decimal_places=2, max_digits=25, null=True),
                ),
                (
                    "volume_24h_usd",
                    models.DecimalField(decimal_places=2, max_digits=25, null=True),
                ),
                ("last_updated", models.DateTimeField(null=True)),
                ("stored_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.currency"),
                ),
                (
                    "provider",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.provider"),
                ),
            ],
            options={
                "ordering": ["-stored_at"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("block_number", models.PositiveIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, verbose_name="created_at"),
                ),
                ("stored_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.currency"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("currency", "provider", "block_number")},
            },
        ),
    ]
